### ISSUE TITLE
Using Pillow-SIMD reports PILLOW_VERSION not found

### ISSUE THREAD

**Issue by shivanraptor** [ftarlao/check-media-integrity#9]
Hi, me again. I tried to replace `Pillow` with `Pillow-SIMD` in macOS 10.16 Catalina. Pillow has been removed and the Pillow-SIMD version I installed via `pip3` is `pillow-simd-7.0.0.post3`. The output is as follow:

```
$ ./check_mi.py -l 2 ~/Desktop/error.jpg            
Traceback (most recent call last):
  File "/Users/adv/Downloads/check-media-integrity-master/./check_mi.py", line 451, in <module>
    main()
  File "/Users/adv/Downloads/check-media-integrity-master/./check_mi.py", line 358, in main
    if not is_pil_simd():
  File "/Users/adv/Downloads/check-media-integrity-master/./check_mi.py", line 289, in is_pil_simd
    return 'post' in PIL.PILLOW_VERSION
AttributeError: module 'PIL' has no attribute 'PILLOW_VERSION'
```

**Comment by ftarlao** [comment]
The instructions states that the script works with Pillow version <7, but I'm going to merge one push request that solves this issue in few days

**Comment by ftarlao** [comment]
Perhaps fixed, try

**Comment by shivanraptor** [comment]
Yes, it's fixed now, thanks.
